language: rust

dist: trusty
sudo: false

os:
  - linux
  - osx
  - osx_image: xcode12
rust:
  - stable
  - nightly

matrix:
  fast_finish: true

branches:
  only:
    - master

before_script:
  - git submodule update --init

script:
  - travis_wait cargo build --verbose
  - cargo test --verbose
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./.travis-ios.sh; fi

notifications:
  email:
    recipients:
      - antiagainst@gmail.com
    on_success: change
    on_failure: always
